/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
Swagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.19
 */
import {useMutation, useQuery} from '@tanstack/react-query'
import type {
    MutationFunction,
    QueryFunction,
    QueryKey,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query'
import {TMDBInstance} from '../../axios'
import type {ErrorType} from '../../axios'
export type V1LoginUserParams = {
    /**
     * The user name for login
     */
    username?: string
    /**
     * The password for login in clear text
     */
    password?: string
}

export type V1GetInventory200 = {[key: string]: number}

export type V1UploadFileParams = {
    /**
     * Additional Metadata
     */
    additionalMetadata?: string
}

export type V1UpdatePetWithFormParams = {
    /**
     * Name of pet that needs to be updated
     */
    name?: string
    /**
     * Status of pet that needs to be updated
     */
    status?: string
}

export type V1FindPetsByTagsParams = {
    /**
     * Tags to filter by
     */
    tags?: string[]
}

export type V1FindPetsByStatusStatus =
    (typeof V1FindPetsByStatusStatus)[keyof typeof V1FindPetsByStatusStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const V1FindPetsByStatusStatus = {
    available: 'available',
    pending: 'pending',
    sold: 'sold',
} as const

export type V1FindPetsByStatusParams = {
    /**
     * Status values that need to be considered for filter
     */
    status?: V1FindPetsByStatusStatus
}

/**
 * Pet object that needs to be added to the store
 */
export type PetBody = Pet

export interface ApiResponse {
    code?: number
    message?: string
    type?: string
}

/**
 * pet status in the store
 */
export type PetStatus = (typeof PetStatus)[keyof typeof PetStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetStatus = {
    available: 'available',
    pending: 'pending',
    sold: 'sold',
} as const

export interface Tag {
    id?: number
    name?: string
}

export interface Pet {
    category?: Category
    id?: number
    name: string
    photoUrls: string[]
    /** pet status in the store */
    status?: PetStatus
    tags?: Tag[]
}

export interface User {
    email?: string
    firstName?: string
    id?: number
    lastName?: string
    password?: string
    phone?: string
    username?: string
    /** User Status */
    userStatus?: number
}

/**
 * List of user object
 */
export type UserArrayBody = User[]

export interface Category {
    id?: number
    name?: string
}

export interface Address {
    city?: string
    state?: string
    street?: string
    zip?: string
}

export interface Customer {
    address?: Address[]
    id?: number
    username?: string
}

/**
 * Order Status
 */
export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderStatus = {
    placed: 'placed',
    approved: 'approved',
    delivered: 'delivered',
} as const

export interface Order {
    complete?: boolean
    id?: number
    petId?: number
    quantity?: number
    shipDate?: string
    /** Order Status */
    status?: OrderStatus
}

/**
 * Update an existing pet by Id
 * @summary Update an existing pet
 */
export const v1UpdatePet = (pet: Pet) => {
    return TMDBInstance<Pet>({
        url: `/pet`,
        method: 'PUT',
        headers: {'Content-Type': 'application/json'},
        data: pet,
    })
}

export const getV1UpdatePetMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1UpdatePet>>,
        TError,
        {data: Pet},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1UpdatePet>>,
    TError,
    {data: Pet},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1UpdatePet>>,
        {data: Pet}
    > = (props) => {
        const {data} = props ?? {}

        return v1UpdatePet(data)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1UpdatePetMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1UpdatePet>>
>
export type V1UpdatePetMutationBody = Pet
export type V1UpdatePetMutationError = ErrorType<void>

/**
 * @summary Update an existing pet
 */
export const useV1UpdatePet = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1UpdatePet>>,
        TError,
        {data: Pet},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1UpdatePet>>,
    TError,
    {data: Pet},
    TContext
> => {
    const mutationOptions = getV1UpdatePetMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * Add a new pet to the store
 * @summary Add a new pet to the store
 */
export const v1AddPet = (pet: Pet) => {
    return TMDBInstance<Pet>({
        url: `/pet`,
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        data: pet,
    })
}

export const getV1AddPetMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1AddPet>>,
        TError,
        {data: Pet},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1AddPet>>,
    TError,
    {data: Pet},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1AddPet>>,
        {data: Pet}
    > = (props) => {
        const {data} = props ?? {}

        return v1AddPet(data)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1AddPetMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1AddPet>>
>
export type V1AddPetMutationBody = Pet
export type V1AddPetMutationError = ErrorType<void>

/**
 * @summary Add a new pet to the store
 */
export const useV1AddPet = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1AddPet>>,
        TError,
        {data: Pet},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1AddPet>>,
    TError,
    {data: Pet},
    TContext
> => {
    const mutationOptions = getV1AddPetMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * Multiple status values can be provided with comma separated strings
 * @summary Finds Pets by status
 */
export const v1FindPetsByStatus = (
    params?: V1FindPetsByStatusParams,
    signal?: AbortSignal,
) => {
    return TMDBInstance<Pet[]>({
        url: `/pet/findByStatus`,
        method: 'GET',
        params,
        signal,
    })
}

export const getV1FindPetsByStatusQueryKey = (
    params?: V1FindPetsByStatusParams,
) => {
    return [`/pet/findByStatus`, ...(params ? [params] : [])] as const
}

export const getV1FindPetsByStatusQueryOptions = <
    TData = Awaited<ReturnType<typeof v1FindPetsByStatus>>,
    TError = ErrorType<void>,
>(
    params?: V1FindPetsByStatusParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1FindPetsByStatus>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getV1FindPetsByStatusQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof v1FindPetsByStatus>>
    > = ({signal}) => v1FindPetsByStatus(params, signal)

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof v1FindPetsByStatus>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type V1FindPetsByStatusQueryResult = NonNullable<
    Awaited<ReturnType<typeof v1FindPetsByStatus>>
>
export type V1FindPetsByStatusQueryError = ErrorType<void>

/**
 * @summary Finds Pets by status
 */
export const useV1FindPetsByStatus = <
    TData = Awaited<ReturnType<typeof v1FindPetsByStatus>>,
    TError = ErrorType<void>,
>(
    params?: V1FindPetsByStatusParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1FindPetsByStatus>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getV1FindPetsByStatusQueryOptions(params, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 */
export const v1FindPetsByTags = (
    params?: V1FindPetsByTagsParams,
    signal?: AbortSignal,
) => {
    return TMDBInstance<Pet[]>({
        url: `/pet/findByTags`,
        method: 'GET',
        params,
        signal,
    })
}

export const getV1FindPetsByTagsQueryKey = (
    params?: V1FindPetsByTagsParams,
) => {
    return [`/pet/findByTags`, ...(params ? [params] : [])] as const
}

export const getV1FindPetsByTagsQueryOptions = <
    TData = Awaited<ReturnType<typeof v1FindPetsByTags>>,
    TError = ErrorType<void>,
>(
    params?: V1FindPetsByTagsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1FindPetsByTags>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getV1FindPetsByTagsQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof v1FindPetsByTags>>
    > = ({signal}) => v1FindPetsByTags(params, signal)

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof v1FindPetsByTags>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type V1FindPetsByTagsQueryResult = NonNullable<
    Awaited<ReturnType<typeof v1FindPetsByTags>>
>
export type V1FindPetsByTagsQueryError = ErrorType<void>

/**
 * @summary Finds Pets by tags
 */
export const useV1FindPetsByTags = <
    TData = Awaited<ReturnType<typeof v1FindPetsByTags>>,
    TError = ErrorType<void>,
>(
    params?: V1FindPetsByTagsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1FindPetsByTags>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getV1FindPetsByTagsQueryOptions(params, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * Returns a single pet
 * @summary Find pet by ID
 */
export const v1GetPetById = (petId: number, signal?: AbortSignal) => {
    return TMDBInstance<Pet>({url: `/pet/${petId}`, method: 'GET', signal})
}

export const getV1GetPetByIdQueryKey = (petId: number) => {
    return [`/pet/${petId}`] as const
}

export const getV1GetPetByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof v1GetPetById>>,
    TError = ErrorType<void>,
>(
    petId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1GetPetById>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getV1GetPetByIdQueryKey(petId)

    const queryFn: QueryFunction<Awaited<ReturnType<typeof v1GetPetById>>> = ({
        signal,
    }) => v1GetPetById(petId, signal)

    return {
        queryKey,
        queryFn,
        enabled: !!petId,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof v1GetPetById>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type V1GetPetByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof v1GetPetById>>
>
export type V1GetPetByIdQueryError = ErrorType<void>

/**
 * @summary Find pet by ID
 */
export const useV1GetPetById = <
    TData = Awaited<ReturnType<typeof v1GetPetById>>,
    TError = ErrorType<void>,
>(
    petId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1GetPetById>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getV1GetPetByIdQueryOptions(petId, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * @summary Updates a pet in the store with form data
 */
export const v1UpdatePetWithForm = (
    petId: number,
    params?: V1UpdatePetWithFormParams,
) => {
    return TMDBInstance<unknown>({url: `/pet/${petId}`, method: 'POST', params})
}

export const getV1UpdatePetWithFormMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1UpdatePetWithForm>>,
        TError,
        {petId: number; params?: V1UpdatePetWithFormParams},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1UpdatePetWithForm>>,
    TError,
    {petId: number; params?: V1UpdatePetWithFormParams},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1UpdatePetWithForm>>,
        {petId: number; params?: V1UpdatePetWithFormParams}
    > = (props) => {
        const {petId, params} = props ?? {}

        return v1UpdatePetWithForm(petId, params)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1UpdatePetWithFormMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1UpdatePetWithForm>>
>

export type V1UpdatePetWithFormMutationError = ErrorType<void>

/**
 * @summary Updates a pet in the store with form data
 */
export const useV1UpdatePetWithForm = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1UpdatePetWithForm>>,
        TError,
        {petId: number; params?: V1UpdatePetWithFormParams},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1UpdatePetWithForm>>,
    TError,
    {petId: number; params?: V1UpdatePetWithFormParams},
    TContext
> => {
    const mutationOptions = getV1UpdatePetWithFormMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * @summary Deletes a pet
 */
export const v1DeletePet = (petId: number) => {
    return TMDBInstance<unknown>({url: `/pet/${petId}`, method: 'DELETE'})
}

export const getV1DeletePetMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1DeletePet>>,
        TError,
        {petId: number},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1DeletePet>>,
    TError,
    {petId: number},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1DeletePet>>,
        {petId: number}
    > = (props) => {
        const {petId} = props ?? {}

        return v1DeletePet(petId)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1DeletePetMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1DeletePet>>
>

export type V1DeletePetMutationError = ErrorType<void>

/**
 * @summary Deletes a pet
 */
export const useV1DeletePet = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1DeletePet>>,
        TError,
        {petId: number},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1DeletePet>>,
    TError,
    {petId: number},
    TContext
> => {
    const mutationOptions = getV1DeletePetMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * @summary uploads an image
 */
export const v1UploadFile = (
    petId: number,
    v1UploadFileBody: Blob,
    params?: V1UploadFileParams,
) => {
    return TMDBInstance<ApiResponse>({
        url: `/pet/${petId}/uploadImage`,
        method: 'POST',
        headers: {'Content-Type': 'application/octet-stream'},
        data: v1UploadFileBody,
        params,
    })
}

export const getV1UploadFileMutationOptions = <
    TError = ErrorType<unknown>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1UploadFile>>,
        TError,
        {petId: number; data: Blob; params?: V1UploadFileParams},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1UploadFile>>,
    TError,
    {petId: number; data: Blob; params?: V1UploadFileParams},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1UploadFile>>,
        {petId: number; data: Blob; params?: V1UploadFileParams}
    > = (props) => {
        const {petId, data, params} = props ?? {}

        return v1UploadFile(petId, data, params)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1UploadFileMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1UploadFile>>
>
export type V1UploadFileMutationBody = Blob
export type V1UploadFileMutationError = ErrorType<unknown>

/**
 * @summary uploads an image
 */
export const useV1UploadFile = <
    TError = ErrorType<unknown>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1UploadFile>>,
        TError,
        {petId: number; data: Blob; params?: V1UploadFileParams},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1UploadFile>>,
    TError,
    {petId: number; data: Blob; params?: V1UploadFileParams},
    TContext
> => {
    const mutationOptions = getV1UploadFileMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * Returns a map of status codes to quantities
 * @summary Returns pet inventories by status
 */
export const v1GetInventory = (signal?: AbortSignal) => {
    return TMDBInstance<V1GetInventory200>({
        url: `/store/inventory`,
        method: 'GET',
        signal,
    })
}

export const getV1GetInventoryQueryKey = () => {
    return [`/store/inventory`] as const
}

export const getV1GetInventoryQueryOptions = <
    TData = Awaited<ReturnType<typeof v1GetInventory>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof v1GetInventory>>,
            TError,
            TData
        >
    >
}) => {
    const {query: queryOptions} = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getV1GetInventoryQueryKey()

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof v1GetInventory>>
    > = ({signal}) => v1GetInventory(signal)

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof v1GetInventory>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type V1GetInventoryQueryResult = NonNullable<
    Awaited<ReturnType<typeof v1GetInventory>>
>
export type V1GetInventoryQueryError = ErrorType<unknown>

/**
 * @summary Returns pet inventories by status
 */
export const useV1GetInventory = <
    TData = Awaited<ReturnType<typeof v1GetInventory>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof v1GetInventory>>,
            TError,
            TData
        >
    >
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getV1GetInventoryQueryOptions(options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * Place a new order in the store
 * @summary Place an order for a pet
 */
export const v1PlaceOrder = (order: Order) => {
    return TMDBInstance<Order>({
        url: `/store/order`,
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        data: order,
    })
}

export const getV1PlaceOrderMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1PlaceOrder>>,
        TError,
        {data: Order},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1PlaceOrder>>,
    TError,
    {data: Order},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1PlaceOrder>>,
        {data: Order}
    > = (props) => {
        const {data} = props ?? {}

        return v1PlaceOrder(data)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1PlaceOrderMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1PlaceOrder>>
>
export type V1PlaceOrderMutationBody = Order
export type V1PlaceOrderMutationError = ErrorType<void>

/**
 * @summary Place an order for a pet
 */
export const useV1PlaceOrder = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1PlaceOrder>>,
        TError,
        {data: Order},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1PlaceOrder>>,
    TError,
    {data: Order},
    TContext
> => {
    const mutationOptions = getV1PlaceOrderMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
 * @summary Find purchase order by ID
 */
export const v1GetOrderById = (orderId: number, signal?: AbortSignal) => {
    return TMDBInstance<Order>({
        url: `/store/order/${orderId}`,
        method: 'GET',
        signal,
    })
}

export const getV1GetOrderByIdQueryKey = (orderId: number) => {
    return [`/store/order/${orderId}`] as const
}

export const getV1GetOrderByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof v1GetOrderById>>,
    TError = ErrorType<void>,
>(
    orderId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1GetOrderById>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getV1GetOrderByIdQueryKey(orderId)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof v1GetOrderById>>
    > = ({signal}) => v1GetOrderById(orderId, signal)

    return {
        queryKey,
        queryFn,
        enabled: !!orderId,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof v1GetOrderById>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type V1GetOrderByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof v1GetOrderById>>
>
export type V1GetOrderByIdQueryError = ErrorType<void>

/**
 * @summary Find purchase order by ID
 */
export const useV1GetOrderById = <
    TData = Awaited<ReturnType<typeof v1GetOrderById>>,
    TError = ErrorType<void>,
>(
    orderId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1GetOrderById>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getV1GetOrderByIdQueryOptions(orderId, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
 * @summary Delete purchase order by ID
 */
export const v1DeleteOrder = (orderId: number) => {
    return TMDBInstance<unknown>({
        url: `/store/order/${orderId}`,
        method: 'DELETE',
    })
}

export const getV1DeleteOrderMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1DeleteOrder>>,
        TError,
        {orderId: number},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1DeleteOrder>>,
    TError,
    {orderId: number},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1DeleteOrder>>,
        {orderId: number}
    > = (props) => {
        const {orderId} = props ?? {}

        return v1DeleteOrder(orderId)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1DeleteOrderMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1DeleteOrder>>
>

export type V1DeleteOrderMutationError = ErrorType<void>

/**
 * @summary Delete purchase order by ID
 */
export const useV1DeleteOrder = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1DeleteOrder>>,
        TError,
        {orderId: number},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1DeleteOrder>>,
    TError,
    {orderId: number},
    TContext
> => {
    const mutationOptions = getV1DeleteOrderMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * This can only be done by the logged in user.
 * @summary Create user
 */
export const v1CreateUser = (user: User) => {
    return TMDBInstance<User>({
        url: `/user`,
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        data: user,
    })
}

export const getV1CreateUserMutationOptions = <
    TError = ErrorType<User>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1CreateUser>>,
        TError,
        {data: User},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1CreateUser>>,
    TError,
    {data: User},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1CreateUser>>,
        {data: User}
    > = (props) => {
        const {data} = props ?? {}

        return v1CreateUser(data)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1CreateUserMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1CreateUser>>
>
export type V1CreateUserMutationBody = User
export type V1CreateUserMutationError = ErrorType<User>

/**
 * @summary Create user
 */
export const useV1CreateUser = <
    TError = ErrorType<User>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1CreateUser>>,
        TError,
        {data: User},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1CreateUser>>,
    TError,
    {data: User},
    TContext
> => {
    const mutationOptions = getV1CreateUserMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * Creates list of users with given input array
 * @summary Creates list of users with given input array
 */
export const v1CreateUsersWithListInput = (user: User[]) => {
    return TMDBInstance<User>({
        url: `/user/createWithList`,
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        data: user,
    })
}

export const getV1CreateUsersWithListInputMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1CreateUsersWithListInput>>,
        TError,
        {data: User[]},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1CreateUsersWithListInput>>,
    TError,
    {data: User[]},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1CreateUsersWithListInput>>,
        {data: User[]}
    > = (props) => {
        const {data} = props ?? {}

        return v1CreateUsersWithListInput(data)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1CreateUsersWithListInputMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1CreateUsersWithListInput>>
>
export type V1CreateUsersWithListInputMutationBody = User[]
export type V1CreateUsersWithListInputMutationError = ErrorType<void>

/**
 * @summary Creates list of users with given input array
 */
export const useV1CreateUsersWithListInput = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1CreateUsersWithListInput>>,
        TError,
        {data: User[]},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1CreateUsersWithListInput>>,
    TError,
    {data: User[]},
    TContext
> => {
    const mutationOptions =
        getV1CreateUsersWithListInputMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * @summary Logs user into the system
 */
export const v1LoginUser = (
    params?: V1LoginUserParams,
    signal?: AbortSignal,
) => {
    return TMDBInstance<string>({
        url: `/user/login`,
        method: 'GET',
        params,
        signal,
    })
}

export const getV1LoginUserQueryKey = (params?: V1LoginUserParams) => {
    return [`/user/login`, ...(params ? [params] : [])] as const
}

export const getV1LoginUserQueryOptions = <
    TData = Awaited<ReturnType<typeof v1LoginUser>>,
    TError = ErrorType<void>,
>(
    params?: V1LoginUserParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1LoginUser>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getV1LoginUserQueryKey(params)

    const queryFn: QueryFunction<Awaited<ReturnType<typeof v1LoginUser>>> = ({
        signal,
    }) => v1LoginUser(params, signal)

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof v1LoginUser>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type V1LoginUserQueryResult = NonNullable<
    Awaited<ReturnType<typeof v1LoginUser>>
>
export type V1LoginUserQueryError = ErrorType<void>

/**
 * @summary Logs user into the system
 */
export const useV1LoginUser = <
    TData = Awaited<ReturnType<typeof v1LoginUser>>,
    TError = ErrorType<void>,
>(
    params?: V1LoginUserParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1LoginUser>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getV1LoginUserQueryOptions(params, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * @summary Logs out current logged in user session
 */
export const v1LogoutUser = (signal?: AbortSignal) => {
    return TMDBInstance<void>({url: `/user/logout`, method: 'GET', signal})
}

export const getV1LogoutUserQueryKey = () => {
    return [`/user/logout`] as const
}

export const getV1LogoutUserQueryOptions = <
    TData = Awaited<ReturnType<typeof v1LogoutUser>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof v1LogoutUser>>, TError, TData>
    >
}) => {
    const {query: queryOptions} = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getV1LogoutUserQueryKey()

    const queryFn: QueryFunction<Awaited<ReturnType<typeof v1LogoutUser>>> = ({
        signal,
    }) => v1LogoutUser(signal)

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof v1LogoutUser>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type V1LogoutUserQueryResult = NonNullable<
    Awaited<ReturnType<typeof v1LogoutUser>>
>
export type V1LogoutUserQueryError = ErrorType<void>

/**
 * @summary Logs out current logged in user session
 */
export const useV1LogoutUser = <
    TData = Awaited<ReturnType<typeof v1LogoutUser>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof v1LogoutUser>>, TError, TData>
    >
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getV1LogoutUserQueryOptions(options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * @summary Get user by user name
 */
export const v1GetUserByName = (username: string, signal?: AbortSignal) => {
    return TMDBInstance<User>({url: `/user/${username}`, method: 'GET', signal})
}

export const getV1GetUserByNameQueryKey = (username: string) => {
    return [`/user/${username}`] as const
}

export const getV1GetUserByNameQueryOptions = <
    TData = Awaited<ReturnType<typeof v1GetUserByName>>,
    TError = ErrorType<void>,
>(
    username: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1GetUserByName>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getV1GetUserByNameQueryKey(username)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof v1GetUserByName>>
    > = ({signal}) => v1GetUserByName(username, signal)

    return {
        queryKey,
        queryFn,
        enabled: !!username,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof v1GetUserByName>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type V1GetUserByNameQueryResult = NonNullable<
    Awaited<ReturnType<typeof v1GetUserByName>>
>
export type V1GetUserByNameQueryError = ErrorType<void>

/**
 * @summary Get user by user name
 */
export const useV1GetUserByName = <
    TData = Awaited<ReturnType<typeof v1GetUserByName>>,
    TError = ErrorType<void>,
>(
    username: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof v1GetUserByName>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getV1GetUserByNameQueryOptions(username, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * This can only be done by the logged in user.
 * @summary Update user
 */
export const v1UpdateUser = (username: string, user: User) => {
    return TMDBInstance<void>({
        url: `/user/${username}`,
        method: 'PUT',
        headers: {'Content-Type': 'application/json'},
        data: user,
    })
}

export const getV1UpdateUserMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1UpdateUser>>,
        TError,
        {username: string; data: User},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1UpdateUser>>,
    TError,
    {username: string; data: User},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1UpdateUser>>,
        {username: string; data: User}
    > = (props) => {
        const {username, data} = props ?? {}

        return v1UpdateUser(username, data)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1UpdateUserMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1UpdateUser>>
>
export type V1UpdateUserMutationBody = User
export type V1UpdateUserMutationError = ErrorType<void>

/**
 * @summary Update user
 */
export const useV1UpdateUser = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1UpdateUser>>,
        TError,
        {username: string; data: User},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1UpdateUser>>,
    TError,
    {username: string; data: User},
    TContext
> => {
    const mutationOptions = getV1UpdateUserMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * This can only be done by the logged in user.
 * @summary Delete user
 */
export const v1DeleteUser = (username: string) => {
    return TMDBInstance<unknown>({url: `/user/${username}`, method: 'DELETE'})
}

export const getV1DeleteUserMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1DeleteUser>>,
        TError,
        {username: string},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof v1DeleteUser>>,
    TError,
    {username: string},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof v1DeleteUser>>,
        {username: string}
    > = (props) => {
        const {username} = props ?? {}

        return v1DeleteUser(username)
    }

    return {mutationFn, ...mutationOptions}
}

export type V1DeleteUserMutationResult = NonNullable<
    Awaited<ReturnType<typeof v1DeleteUser>>
>

export type V1DeleteUserMutationError = ErrorType<void>

/**
 * @summary Delete user
 */
export const useV1DeleteUser = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof v1DeleteUser>>,
        TError,
        {username: string},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof v1DeleteUser>>,
    TError,
    {username: string},
    TContext
> => {
    const mutationOptions = getV1DeleteUserMutationOptions(options)

    return useMutation(mutationOptions)
}
