/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Swagger Petstore - OpenAPI 3.0
 * This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
Swagger at [http://swagger.io](http://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
You can now help us improve the API whether it's by making changes to the definition itself or to the code.
That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

Some useful links:
- [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
- [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 * OpenAPI spec version: 1.0.19
 */
import {useMutation, useQuery} from '@tanstack/react-query'
import type {
    MutationFunction,
    QueryFunction,
    QueryKey,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from '@tanstack/react-query'
import {TMDBInstance} from '../../axios'
import type {ErrorType} from '../../axios'
export type LoginUserParams = {
    /**
     * The user name for login
     */
    username?: string
    /**
     * The password for login in clear text
     */
    password?: string
}

export type GetInventory200 = {[key: string]: number}

export type UploadFileParams = {
    /**
     * Additional Metadata
     */
    additionalMetadata?: string
}

export type UpdatePetWithFormParams = {
    /**
     * Name of pet that needs to be updated
     */
    name?: string
    /**
     * Status of pet that needs to be updated
     */
    status?: string
}

export type FindPetsByTagsParams = {
    /**
     * Tags to filter by
     */
    tags?: string[]
}

export type FindPetsByStatusStatus =
    (typeof FindPetsByStatusStatus)[keyof typeof FindPetsByStatusStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FindPetsByStatusStatus = {
    available: 'available',
    pending: 'pending',
    sold: 'sold',
} as const

export type FindPetsByStatusParams = {
    /**
     * Status values that need to be considered for filter
     */
    status?: FindPetsByStatusStatus
}

/**
 * Pet object that needs to be added to the store
 */
export type PetBody = Pet

export interface ApiResponse {
    code?: number
    message?: string
    type?: string
}

/**
 * pet status in the store
 */
export type PetStatus = (typeof PetStatus)[keyof typeof PetStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PetStatus = {
    available: 'available',
    pending: 'pending',
    sold: 'sold',
} as const

export interface Tag {
    id?: number
    name?: string
}

export interface Pet {
    category?: Category
    id?: number
    name: string
    photoUrls: string[]
    /** pet status in the store */
    status?: PetStatus
    tags?: Tag[]
}

export interface User {
    email?: string
    firstName?: string
    id?: number
    lastName?: string
    password?: string
    phone?: string
    username?: string
    /** User Status */
    userStatus?: number
}

/**
 * List of user object
 */
export type UserArrayBody = User[]

export interface Category {
    id?: number
    name?: string
}

export interface Address {
    city?: string
    state?: string
    street?: string
    zip?: string
}

export interface Customer {
    address?: Address[]
    id?: number
    username?: string
}

/**
 * Order Status
 */
export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderStatus = {
    placed: 'placed',
    approved: 'approved',
    delivered: 'delivered',
} as const

export interface Order {
    complete?: boolean
    id?: number
    petId?: number
    quantity?: number
    shipDate?: string
    /** Order Status */
    status?: OrderStatus
}

/**
 * Update an existing pet by Id
 * @summary Update an existing pet
 */
export const updatePet = (pet: Pet) => {
    return TMDBInstance<Pet>({
        url: `/pet`,
        method: 'PUT',
        headers: {'Content-Type': 'application/json'},
        data: pet,
    })
}

export const getUpdatePetMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updatePet>>,
        TError,
        {data: Pet},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof updatePet>>,
    TError,
    {data: Pet},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updatePet>>,
        {data: Pet}
    > = (props) => {
        const {data} = props ?? {}

        return updatePet(data)
    }

    return {mutationFn, ...mutationOptions}
}

export type UpdatePetMutationResult = NonNullable<
    Awaited<ReturnType<typeof updatePet>>
>
export type UpdatePetMutationBody = Pet
export type UpdatePetMutationError = ErrorType<void>

/**
 * @summary Update an existing pet
 */
export const useUpdatePet = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updatePet>>,
        TError,
        {data: Pet},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof updatePet>>,
    TError,
    {data: Pet},
    TContext
> => {
    const mutationOptions = getUpdatePetMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * Add a new pet to the store
 * @summary Add a new pet to the store
 */
export const addPet = (pet: Pet) => {
    return TMDBInstance<Pet>({
        url: `/pet`,
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        data: pet,
    })
}

export const getAddPetMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof addPet>>,
        TError,
        {data: Pet},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof addPet>>,
    TError,
    {data: Pet},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof addPet>>,
        {data: Pet}
    > = (props) => {
        const {data} = props ?? {}

        return addPet(data)
    }

    return {mutationFn, ...mutationOptions}
}

export type AddPetMutationResult = NonNullable<
    Awaited<ReturnType<typeof addPet>>
>
export type AddPetMutationBody = Pet
export type AddPetMutationError = ErrorType<void>

/**
 * @summary Add a new pet to the store
 */
export const useAddPet = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof addPet>>,
        TError,
        {data: Pet},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof addPet>>,
    TError,
    {data: Pet},
    TContext
> => {
    const mutationOptions = getAddPetMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * Multiple status values can be provided with comma separated strings
 * @summary Finds Pets by status
 */
export const findPetsByStatus = (
    params?: FindPetsByStatusParams,
    signal?: AbortSignal,
) => {
    return TMDBInstance<Pet[]>({
        url: `/pet/findByStatus`,
        method: 'GET',
        params,
        signal,
    })
}

export const getFindPetsByStatusQueryKey = (
    params?: FindPetsByStatusParams,
) => {
    return [`/pet/findByStatus`, ...(params ? [params] : [])] as const
}

export const getFindPetsByStatusQueryOptions = <
    TData = Awaited<ReturnType<typeof findPetsByStatus>>,
    TError = ErrorType<void>,
>(
    params?: FindPetsByStatusParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof findPetsByStatus>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getFindPetsByStatusQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof findPetsByStatus>>
    > = ({signal}) => findPetsByStatus(params, signal)

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof findPetsByStatus>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type FindPetsByStatusQueryResult = NonNullable<
    Awaited<ReturnType<typeof findPetsByStatus>>
>
export type FindPetsByStatusQueryError = ErrorType<void>

/**
 * @summary Finds Pets by status
 */
export const useFindPetsByStatus = <
    TData = Awaited<ReturnType<typeof findPetsByStatus>>,
    TError = ErrorType<void>,
>(
    params?: FindPetsByStatusParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof findPetsByStatus>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getFindPetsByStatusQueryOptions(params, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 */
export const findPetsByTags = (
    params?: FindPetsByTagsParams,
    signal?: AbortSignal,
) => {
    return TMDBInstance<Pet[]>({
        url: `/pet/findByTags`,
        method: 'GET',
        params,
        signal,
    })
}

export const getFindPetsByTagsQueryKey = (params?: FindPetsByTagsParams) => {
    return [`/pet/findByTags`, ...(params ? [params] : [])] as const
}

export const getFindPetsByTagsQueryOptions = <
    TData = Awaited<ReturnType<typeof findPetsByTags>>,
    TError = ErrorType<void>,
>(
    params?: FindPetsByTagsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof findPetsByTags>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getFindPetsByTagsQueryKey(params)

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof findPetsByTags>>
    > = ({signal}) => findPetsByTags(params, signal)

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof findPetsByTags>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type FindPetsByTagsQueryResult = NonNullable<
    Awaited<ReturnType<typeof findPetsByTags>>
>
export type FindPetsByTagsQueryError = ErrorType<void>

/**
 * @summary Finds Pets by tags
 */
export const useFindPetsByTags = <
    TData = Awaited<ReturnType<typeof findPetsByTags>>,
    TError = ErrorType<void>,
>(
    params?: FindPetsByTagsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof findPetsByTags>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getFindPetsByTagsQueryOptions(params, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * Returns a single pet
 * @summary Find pet by ID
 */
export const getPetById = (petId: number, signal?: AbortSignal) => {
    return TMDBInstance<Pet>({url: `/pet/${petId}`, method: 'GET', signal})
}

export const getGetPetByIdQueryKey = (petId: number) => {
    return [`/pet/${petId}`] as const
}

export const getGetPetByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getPetById>>,
    TError = ErrorType<void>,
>(
    petId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPetById>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getGetPetByIdQueryKey(petId)

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPetById>>> = ({
        signal,
    }) => getPetById(petId, signal)

    return {
        queryKey,
        queryFn,
        enabled: !!petId,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getPetById>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type GetPetByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getPetById>>
>
export type GetPetByIdQueryError = ErrorType<void>

/**
 * @summary Find pet by ID
 */
export const useGetPetById = <
    TData = Awaited<ReturnType<typeof getPetById>>,
    TError = ErrorType<void>,
>(
    petId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getPetById>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getGetPetByIdQueryOptions(petId, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * @summary Updates a pet in the store with form data
 */
export const updatePetWithForm = (
    petId: number,
    params?: UpdatePetWithFormParams,
) => {
    return TMDBInstance<unknown>({url: `/pet/${petId}`, method: 'POST', params})
}

export const getUpdatePetWithFormMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updatePetWithForm>>,
        TError,
        {petId: number; params?: UpdatePetWithFormParams},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof updatePetWithForm>>,
    TError,
    {petId: number; params?: UpdatePetWithFormParams},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updatePetWithForm>>,
        {petId: number; params?: UpdatePetWithFormParams}
    > = (props) => {
        const {petId, params} = props ?? {}

        return updatePetWithForm(petId, params)
    }

    return {mutationFn, ...mutationOptions}
}

export type UpdatePetWithFormMutationResult = NonNullable<
    Awaited<ReturnType<typeof updatePetWithForm>>
>

export type UpdatePetWithFormMutationError = ErrorType<void>

/**
 * @summary Updates a pet in the store with form data
 */
export const useUpdatePetWithForm = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updatePetWithForm>>,
        TError,
        {petId: number; params?: UpdatePetWithFormParams},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof updatePetWithForm>>,
    TError,
    {petId: number; params?: UpdatePetWithFormParams},
    TContext
> => {
    const mutationOptions = getUpdatePetWithFormMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * @summary Deletes a pet
 */
export const deletePet = (petId: number) => {
    return TMDBInstance<unknown>({url: `/pet/${petId}`, method: 'DELETE'})
}

export const getDeletePetMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deletePet>>,
        TError,
        {petId: number},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof deletePet>>,
    TError,
    {petId: number},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deletePet>>,
        {petId: number}
    > = (props) => {
        const {petId} = props ?? {}

        return deletePet(petId)
    }

    return {mutationFn, ...mutationOptions}
}

export type DeletePetMutationResult = NonNullable<
    Awaited<ReturnType<typeof deletePet>>
>

export type DeletePetMutationError = ErrorType<void>

/**
 * @summary Deletes a pet
 */
export const useDeletePet = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deletePet>>,
        TError,
        {petId: number},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof deletePet>>,
    TError,
    {petId: number},
    TContext
> => {
    const mutationOptions = getDeletePetMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * @summary uploads an image
 */
export const uploadFile = (
    petId: number,
    uploadFileBody: Blob,
    params?: UploadFileParams,
) => {
    return TMDBInstance<ApiResponse>({
        url: `/pet/${petId}/uploadImage`,
        method: 'POST',
        headers: {'Content-Type': 'application/octet-stream'},
        data: uploadFileBody,
        params,
    })
}

export const getUploadFileMutationOptions = <
    TError = ErrorType<unknown>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof uploadFile>>,
        TError,
        {petId: number; data: Blob; params?: UploadFileParams},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof uploadFile>>,
    TError,
    {petId: number; data: Blob; params?: UploadFileParams},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof uploadFile>>,
        {petId: number; data: Blob; params?: UploadFileParams}
    > = (props) => {
        const {petId, data, params} = props ?? {}

        return uploadFile(petId, data, params)
    }

    return {mutationFn, ...mutationOptions}
}

export type UploadFileMutationResult = NonNullable<
    Awaited<ReturnType<typeof uploadFile>>
>
export type UploadFileMutationBody = Blob
export type UploadFileMutationError = ErrorType<unknown>

/**
 * @summary uploads an image
 */
export const useUploadFile = <
    TError = ErrorType<unknown>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof uploadFile>>,
        TError,
        {petId: number; data: Blob; params?: UploadFileParams},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof uploadFile>>,
    TError,
    {petId: number; data: Blob; params?: UploadFileParams},
    TContext
> => {
    const mutationOptions = getUploadFileMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * Returns a map of status codes to quantities
 * @summary Returns pet inventories by status
 */
export const getInventory = (signal?: AbortSignal) => {
    return TMDBInstance<GetInventory200>({
        url: `/store/inventory`,
        method: 'GET',
        signal,
    })
}

export const getGetInventoryQueryKey = () => {
    return [`/store/inventory`] as const
}

export const getGetInventoryQueryOptions = <
    TData = Awaited<ReturnType<typeof getInventory>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getInventory>>, TError, TData>
    >
}) => {
    const {query: queryOptions} = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getGetInventoryQueryKey()

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInventory>>> = ({
        signal,
    }) => getInventory(signal)

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof getInventory>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type GetInventoryQueryResult = NonNullable<
    Awaited<ReturnType<typeof getInventory>>
>
export type GetInventoryQueryError = ErrorType<unknown>

/**
 * @summary Returns pet inventories by status
 */
export const useGetInventory = <
    TData = Awaited<ReturnType<typeof getInventory>>,
    TError = ErrorType<unknown>,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getInventory>>, TError, TData>
    >
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getGetInventoryQueryOptions(options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * Place a new order in the store
 * @summary Place an order for a pet
 */
export const placeOrder = (order: Order) => {
    return TMDBInstance<Order>({
        url: `/store/order`,
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        data: order,
    })
}

export const getPlaceOrderMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof placeOrder>>,
        TError,
        {data: Order},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof placeOrder>>,
    TError,
    {data: Order},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof placeOrder>>,
        {data: Order}
    > = (props) => {
        const {data} = props ?? {}

        return placeOrder(data)
    }

    return {mutationFn, ...mutationOptions}
}

export type PlaceOrderMutationResult = NonNullable<
    Awaited<ReturnType<typeof placeOrder>>
>
export type PlaceOrderMutationBody = Order
export type PlaceOrderMutationError = ErrorType<void>

/**
 * @summary Place an order for a pet
 */
export const usePlaceOrder = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof placeOrder>>,
        TError,
        {data: Order},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof placeOrder>>,
    TError,
    {data: Order},
    TContext
> => {
    const mutationOptions = getPlaceOrderMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
 * @summary Find purchase order by ID
 */
export const getOrderById = (orderId: number, signal?: AbortSignal) => {
    return TMDBInstance<Order>({
        url: `/store/order/${orderId}`,
        method: 'GET',
        signal,
    })
}

export const getGetOrderByIdQueryKey = (orderId: number) => {
    return [`/store/order/${orderId}`] as const
}

export const getGetOrderByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getOrderById>>,
    TError = ErrorType<void>,
>(
    orderId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getOrderById>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getGetOrderByIdQueryKey(orderId)

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrderById>>> = ({
        signal,
    }) => getOrderById(orderId, signal)

    return {
        queryKey,
        queryFn,
        enabled: !!orderId,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getOrderById>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type GetOrderByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getOrderById>>
>
export type GetOrderByIdQueryError = ErrorType<void>

/**
 * @summary Find purchase order by ID
 */
export const useGetOrderById = <
    TData = Awaited<ReturnType<typeof getOrderById>>,
    TError = ErrorType<void>,
>(
    orderId: number,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getOrderById>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getGetOrderByIdQueryOptions(orderId, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * For valid response try integer IDs with value < 1000. Anything above 1000 or nonintegers will generate API errors
 * @summary Delete purchase order by ID
 */
export const deleteOrder = (orderId: number) => {
    return TMDBInstance<unknown>({
        url: `/store/order/${orderId}`,
        method: 'DELETE',
    })
}

export const getDeleteOrderMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteOrder>>,
        TError,
        {orderId: number},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteOrder>>,
    TError,
    {orderId: number},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteOrder>>,
        {orderId: number}
    > = (props) => {
        const {orderId} = props ?? {}

        return deleteOrder(orderId)
    }

    return {mutationFn, ...mutationOptions}
}

export type DeleteOrderMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteOrder>>
>

export type DeleteOrderMutationError = ErrorType<void>

/**
 * @summary Delete purchase order by ID
 */
export const useDeleteOrder = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteOrder>>,
        TError,
        {orderId: number},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof deleteOrder>>,
    TError,
    {orderId: number},
    TContext
> => {
    const mutationOptions = getDeleteOrderMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * This can only be done by the logged in user.
 * @summary Create user
 */
export const createUser = (user: User) => {
    return TMDBInstance<User>({
        url: `/user`,
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        data: user,
    })
}

export const getCreateUserMutationOptions = <
    TError = ErrorType<User>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {data: User},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof createUser>>,
    TError,
    {data: User},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createUser>>,
        {data: User}
    > = (props) => {
        const {data} = props ?? {}

        return createUser(data)
    }

    return {mutationFn, ...mutationOptions}
}

export type CreateUserMutationResult = NonNullable<
    Awaited<ReturnType<typeof createUser>>
>
export type CreateUserMutationBody = User
export type CreateUserMutationError = ErrorType<User>

/**
 * @summary Create user
 */
export const useCreateUser = <
    TError = ErrorType<User>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {data: User},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof createUser>>,
    TError,
    {data: User},
    TContext
> => {
    const mutationOptions = getCreateUserMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * Creates list of users with given input array
 * @summary Creates list of users with given input array
 */
export const createUsersWithListInput = (user: User[]) => {
    return TMDBInstance<User>({
        url: `/user/createWithList`,
        method: 'POST',
        headers: {'Content-Type': 'application/json'},
        data: user,
    })
}

export const getCreateUsersWithListInputMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createUsersWithListInput>>,
        TError,
        {data: User[]},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof createUsersWithListInput>>,
    TError,
    {data: User[]},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof createUsersWithListInput>>,
        {data: User[]}
    > = (props) => {
        const {data} = props ?? {}

        return createUsersWithListInput(data)
    }

    return {mutationFn, ...mutationOptions}
}

export type CreateUsersWithListInputMutationResult = NonNullable<
    Awaited<ReturnType<typeof createUsersWithListInput>>
>
export type CreateUsersWithListInputMutationBody = User[]
export type CreateUsersWithListInputMutationError = ErrorType<void>

/**
 * @summary Creates list of users with given input array
 */
export const useCreateUsersWithListInput = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof createUsersWithListInput>>,
        TError,
        {data: User[]},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof createUsersWithListInput>>,
    TError,
    {data: User[]},
    TContext
> => {
    const mutationOptions = getCreateUsersWithListInputMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * @summary Logs user into the system
 */
export const loginUser = (params?: LoginUserParams, signal?: AbortSignal) => {
    return TMDBInstance<string>({
        url: `/user/login`,
        method: 'GET',
        params,
        signal,
    })
}

export const getLoginUserQueryKey = (params?: LoginUserParams) => {
    return [`/user/login`, ...(params ? [params] : [])] as const
}

export const getLoginUserQueryOptions = <
    TData = Awaited<ReturnType<typeof loginUser>>,
    TError = ErrorType<void>,
>(
    params?: LoginUserParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof loginUser>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getLoginUserQueryKey(params)

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loginUser>>> = ({
        signal,
    }) => loginUser(params, signal)

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof loginUser>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type LoginUserQueryResult = NonNullable<
    Awaited<ReturnType<typeof loginUser>>
>
export type LoginUserQueryError = ErrorType<void>

/**
 * @summary Logs user into the system
 */
export const useLoginUser = <
    TData = Awaited<ReturnType<typeof loginUser>>,
    TError = ErrorType<void>,
>(
    params?: LoginUserParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof loginUser>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getLoginUserQueryOptions(params, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * @summary Logs out current logged in user session
 */
export const logoutUser = (signal?: AbortSignal) => {
    return TMDBInstance<void>({url: `/user/logout`, method: 'GET', signal})
}

export const getLogoutUserQueryKey = () => {
    return [`/user/logout`] as const
}

export const getLogoutUserQueryOptions = <
    TData = Awaited<ReturnType<typeof logoutUser>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>
    >
}) => {
    const {query: queryOptions} = options ?? {}

    const queryKey = queryOptions?.queryKey ?? getLogoutUserQueryKey()

    const queryFn: QueryFunction<Awaited<ReturnType<typeof logoutUser>>> = ({
        signal,
    }) => logoutUser(signal)

    return {queryKey, queryFn, ...queryOptions} as UseQueryOptions<
        Awaited<ReturnType<typeof logoutUser>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type LogoutUserQueryResult = NonNullable<
    Awaited<ReturnType<typeof logoutUser>>
>
export type LogoutUserQueryError = ErrorType<void>

/**
 * @summary Logs out current logged in user session
 */
export const useLogoutUser = <
    TData = Awaited<ReturnType<typeof logoutUser>>,
    TError = ErrorType<void>,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>
    >
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getLogoutUserQueryOptions(options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * @summary Get user by user name
 */
export const getUserByName = (username: string, signal?: AbortSignal) => {
    return TMDBInstance<User>({url: `/user/${username}`, method: 'GET', signal})
}

export const getGetUserByNameQueryKey = (username: string) => {
    return [`/user/${username}`] as const
}

export const getGetUserByNameQueryOptions = <
    TData = Awaited<ReturnType<typeof getUserByName>>,
    TError = ErrorType<void>,
>(
    username: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUserByName>>,
                TError,
                TData
            >
        >
    },
) => {
    const {query: queryOptions} = options ?? {}

    const queryKey =
        queryOptions?.queryKey ?? getGetUserByNameQueryKey(username)

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserByName>>> = ({
        signal,
    }) => getUserByName(username, signal)

    return {
        queryKey,
        queryFn,
        enabled: !!username,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getUserByName>>,
        TError,
        TData
    > & {queryKey: QueryKey}
}

export type GetUserByNameQueryResult = NonNullable<
    Awaited<ReturnType<typeof getUserByName>>
>
export type GetUserByNameQueryError = ErrorType<void>

/**
 * @summary Get user by user name
 */
export const useGetUserByName = <
    TData = Awaited<ReturnType<typeof getUserByName>>,
    TError = ErrorType<void>,
>(
    username: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUserByName>>,
                TError,
                TData
            >
        >
    },
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
    const queryOptions = getGetUserByNameQueryOptions(username, options)

    const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
        queryKey: QueryKey
    }

    query.queryKey = queryOptions.queryKey

    return query
}

/**
 * This can only be done by the logged in user.
 * @summary Update user
 */
export const updateUser = (username: string, user: User) => {
    return TMDBInstance<void>({
        url: `/user/${username}`,
        method: 'PUT',
        headers: {'Content-Type': 'application/json'},
        data: user,
    })
}

export const getUpdateUserMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {username: string; data: User},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    {username: string; data: User},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof updateUser>>,
        {username: string; data: User}
    > = (props) => {
        const {username, data} = props ?? {}

        return updateUser(username, data)
    }

    return {mutationFn, ...mutationOptions}
}

export type UpdateUserMutationResult = NonNullable<
    Awaited<ReturnType<typeof updateUser>>
>
export type UpdateUserMutationBody = User
export type UpdateUserMutationError = ErrorType<void>

/**
 * @summary Update user
 */
export const useUpdateUser = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {username: string; data: User},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof updateUser>>,
    TError,
    {username: string; data: User},
    TContext
> => {
    const mutationOptions = getUpdateUserMutationOptions(options)

    return useMutation(mutationOptions)
}

/**
 * This can only be done by the logged in user.
 * @summary Delete user
 */
export const deleteUser = (username: string) => {
    return TMDBInstance<unknown>({url: `/user/${username}`, method: 'DELETE'})
}

export const getDeleteUserMutationOptions = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {username: string},
        TContext
    >
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    {username: string},
    TContext
> => {
    const {mutation: mutationOptions} = options ?? {}

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteUser>>,
        {username: string}
    > = (props) => {
        const {username} = props ?? {}

        return deleteUser(username)
    }

    return {mutationFn, ...mutationOptions}
}

export type DeleteUserMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteUser>>
>

export type DeleteUserMutationError = ErrorType<void>

/**
 * @summary Delete user
 */
export const useDeleteUser = <
    TError = ErrorType<void>,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {username: string},
        TContext
    >
}): UseMutationResult<
    Awaited<ReturnType<typeof deleteUser>>,
    TError,
    {username: string},
    TContext
> => {
    const mutationOptions = getDeleteUserMutationOptions(options)

    return useMutation(mutationOptions)
}
